#!/bin/bash

#written by chn555 && BigRush
#used for quick post installation setup of new install XFCE Manjaro.


#set flags, right now only verbose
while getopts "v" arg; do
  case $arg in
    v)
      echo "Starting in verbose mode"
      verbose=1;;
    *)
      $arg flag invalid;;
    esac
done

update ()
{
# update system
if [[ $verbose -eq 1 ]]; then
  sudo pacman -Syu --noconfirm
  if [[ $? -eq 0 ]];then
    echo "System update completed successfully, moving on"
  else
      echo "Something went wrong, stopping. check internet connection"
      exit 1
  fi
  #install pacaur if not installed already
  sudo pacman -S pacaur --needed --noconfirm
else
    sudo pacman -Syu --noconfirm >> /tmp/chn-log 2>> /tmp/chn-error-log
    if [[ $? -eq 0 ]];then
      echo "System update completed successfully, moving on"
    else
      echo "Something went wrong, stopping. check internet connection"
      exit 1
    fi
    #install pacaur if not installed already
  sudo pacman -S pacaur --needed --noconfirm >> /tmp/chn-log 2>> /tmp/chn-error-log
fi
}




installation ()
{
  if [[ $verbose -eq 1 ]]; then
    echo "setting keys for download"
    #set keys required for discord install
    gpg --recv-keys 8F0871F202119294
    echo "downloading and installing software"
    printf "\n"
    #a list of programs to be installed
    apps=(git discord vim openssh steam chromium virtualbox ncdu tilix speedtest-cli)
    for app in ${apps[*]}; do
      echo "Installing $app, please wait"
      pacaur -S $app --noconfirm --needed --noedit
      if [[ $? -eq 0 ]]; then
        echo "$app installed successfully"
        printf "\n"
      else
        printf "\n"
        echo "installation of $app failed, see logs"
      fi
      sleep 1
    done
    echo "downloading and installing themes"
    #pacaur -S -needed adapta-gtk-theme-git papirus-icon-theme-git --noconfirm --noedit
    sleep 3
    echo "Setting themes"
    printf "\n"
    #  xfconf-query -c xsettings -p /Net/ThemeName -s "Adapta-Nokto"
    #  xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Adapta"
else
  echo "setting keys for download"
  gpg --recv-keys 8F0871F202119294 >> /tmp/chn-log 2>> /tmp/chn-error-log
  echo "downloading and installing software"
  printf "\n"
  apps=(git discord vim openssh steam chromium virtualbox ncdu tilix speedtest-cli)
  for app in ${apps[*]}; do
    echo "Installing $app, please wait"
    pacaur -S $app --noconfirm --needed --noedit >> /tmp/chn-log 2>> /tmp/chn-error-log
    if [[ $? -eq 0 ]]; then
      echo "$app installed successfully"
      printf "\n"
    else
      printf "\n"
      echo "installation of $app failed, see logs"
    fi
    sleep 1
  done
  echo "downloading and installing themes"
  #pacaur -S -needed adapta-gtk-theme-git papirus-icon-theme-git --noconfirm --noedit >> /tmp/chn-log 2>> /tmp/chn-error-log
  sleep 3
  echo "Setting themes"
  printf "\n"
  #  xfconf-query -c xsettings -p /Net/ThemeName -s "Adapta-Nokto" >> /tmp/chn-log 2>> /tmp/chn-error-log
  #  xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Adapta" >> /tmp/chn-log 2>> /tmp/chn-error-log
fi
}


grub ()
{
if [[ $verbose -eq 1 ]]; then
  #set grub timeout to 0
  sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
  #set hidden timeout to 1 so you can access the grub if you press esc while booting
  sudo sed -i 's/#GRUB_HIDDEN_TIMEOUT=1/GRUB_HIDDEN_TIMEOUT=1/' /etc/default/grub
  #enable hidden timeout
  sudo sed -i 's/#GRUB_HIDDEN_TIMEOUT_QUIET=true/GRUB_HIDDEN_TIMEOUT_QUIET=true/' /etc/default/grub
  #apply settings to grubb
  sudo grub-mkconfig
else

  #set grub timeout to 0
  sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub >> /tmp/chn-log 2>> /tmp/chn-error-log
  #set hidden timeout to 1 so you can access the grub if you press esc while booting
  sudo sed -i 's/#GRUB_HIDDEN_TIMEOUT=1/GRUB_HIDDEN_TIMEOUT=1/' /etc/default/grub >> /tmp/chn-log 2>> /tmp/chn-error-log
  #enable hidden timeout
  sudo sed -i 's/#GRUB_HIDDEN_TIMEOUT_QUIET=true/GRUB_HIDDEN_TIMEOUT_QUIET=true/' /etc/default/grub >> /tmp/chn-log 2>> /tmp/chn-error-log
  #apply settings to grubb
  sudo grub-mkconfig >> /tmp/chn-log 2>> /tmp/chn-error-log
fi
}

keybind ()
{
xmodmap -e "keycode 67=XF86Back NoSymbol XF86Back"
xmodmap -e "keycode 68=XF86Forward NoSymbol XF86Forward"
xmodmap -e "keycode 69=XF86Reload NoSymbol XF86Reload"
xmodmap -e "keycode 72=XF86MonBrightnessDown NoSymbol XF86MonBrightnessDown"
xmodmap -e "keycode 73=XF86MonBrightnessUp NoSymbol XF86MonBrightnessUp"
xmodmap -e "keycode 74=XF86AudioMute NoSymbol XF86AudioMute"
xmodmap -e "keycode 75=XF86AudioLowerVolume NoSymbol XF86AudioLowerVolume"
xmodmap -e "keycode 76=XF86AudioRaiseVolume NoSymbol XF86AudioRaiseVolume"
xmodmap -e "keycode 114= Right End Right"
xmodmap -e "keycode 113= Left Home Right"

#audio keys bind
echo  \"amixer set Master toggle\" > ~/.xbindkeysrc
echo     m:0x0 + c:121  >> ~/.xbindkeysrc
echo   XF86AudioMute  >> ~/.xbindkeysrc
echo \"amixer set PCM 2dB+\" >> ~/.xbindkeysrc
echo     m:0x0 + c:123 >> ~/.xbindkeysrc
echo     XF86AudioRaiseVolume >> ~/.xbindkeysrc
echo \"amixer set PCM 2dB-\" >> ~/.xbindkeysrc
echo    m:0x0 + c:122 >> ~/.xbindkeysrc
echo    XF86AudioLowerVolume  >> ~/.xbindkeysrc
}

linux-samus ()
{
if [[ $verbose -eq 1 ]]; then
  cd ~
  git clone --depth=1 https://github.com/raphael/linux-samus
  bash ~/linux-samus/scripts/setup/audio/enable-audio.sh
  bash ~/linux-samus/scripts/setup/audio/enable-speakers.sh
else
  cd ~
  git clone --depth=1 https://github.com/raphael/linux-samus >> /tmp/chn-log 2>> /tmp/chn-error-log
  bash ~/linux-samus/scripts/setup/audio/enable-audio.sh >> /tmp/chn-log 2>> /tmp/chn-error-log
  bash ~/linux-samus/scripts/setup/audio/enable-speakers.sh >> /tmp/chn-log 2>> /tmp/chn-error-log
fi
}

#not in use yet, needs to be researched
themes()
{
  echo '
  <?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-panel" version="1.0">
  <property name="panels" type="uint" value="1">
    <property name="panel-0" type="empty">
      <property name="position" type="string" value="p=8;x=720;y=884"/>
      <property name="length" type="uint" value="100"/>
      <property name="position-locked" type="bool" value="true"/>
      <property name="plugin-ids" type="array">
        <value type="int" value="8"/>
        <value type="int" value="10"/>
        <value type="int" value="11"/>
        <value type="int" value="14"/>
        <value type="int" value="3"/>
        <value type="int" value="7"/>
        <value type="int" value="9"/>
        <value type="int" value="4"/>
        <value type="int" value="12"/>
        <value type="int" value="6"/>
        <value type="int" value="1"/>
        <value type="int" value="5"/>
        <value type="int" value="2"/>
      </property>
      <property name="role" type="string" value="xfce4-panel-12965750720"/>
      <property name="length-adjust" type="bool" value="true"/>
      <property name="background-style" type="uint" value="0"/>
      <property name="size" type="uint" value="49"/>
      <property name="mode" type="uint" value="0"/>
      <property name="autohide-behavior" type="uint" value="0"/>
      <property name="background-alpha" type="uint" value="0"/>
    </property>
  </property>
  <property name="plugins" type="empty">
    <property name="plugin-2" type="string" value="actions">
      <property name="appearance" type="uint" value="0"/>
      <property name="invert-orientation" type="bool" value="false"/>
      <property name="items" type="array">
        <value type="string" value="-logout-dialog"/>
        <value type="string" value="-switch-user"/>
        <value type="string" value="-separator"/>
        <value type="string" value="+logout"/>
        <value type="string" value="-lock-screen"/>
        <value type="string" value="-hibernate"/>
        <value type="string" value="-suspend"/>
        <value type="string" value="-restart"/>
        <value type="string" value="-shutdown"/>
      </property>
    </property>
    <property name="plugin-6" type="string" value="systray">
      <property name="names-visible" type="array">
        <value type="string" value="pnmixer"/>
        <value type="string" value="manjaro-settings-manager-daemon"/>
        <value type="string" value="networkmanager applet"/>
        <value type="string" value="msm notifier"/>
        <value type="string" value="orage"/>
        <value type="string" value="pamac-tray"/>
        <value type="string" value="blueman-applet"/>
        <value type="string" value="clipman"/>
        <value type="string" value="xfce4-power-manager"/>
        <value type="string" value="pa-applet"/>
        <value type="string" value="xnoise"/>
      </property>
      <property name="size-max" type="uint" value="31"/>
    </property>
    <property name="plugin-3" type="string" value="tasklist">
      <property name="grouping" type="uint" value="1"/>
      <property name="show-handle" type="bool" value="false"/>
      <property name="sort-order" type="uint" value="4"/>
      <property name="show-labels" type="bool" value="false"/>
      <property name="flat-buttons" type="bool" value="true"/>
    </property>
    <property name="plugin-7" type="string" value="separator">
      <property name="expand" type="bool" value="true"/>
      <property name="style" type="uint" value="1"/>
    </property>
    <property name="plugin-8" type="string" value="whiskermenu"/>
    <property name="plugin-5" type="string" value="clock"/>
    <property name="plugin-1" type="string" value="power-manager-plugin"/>
    <property name="plugin-4" type="string" value="netload"/>
    <property name="plugin-9" type="string" value="netload"/>
    <property name="plugin-10" type="string" value="launcher">
      <property name="items" type="array">
        <value type="string" value="15160481181.desktop"/>
      </property>
    </property>
    <property name="plugin-11" type="string" value="launcher">
      <property name="items" type="array">
        <value type="string" value="15160481272.desktop"/>
      </property>
    </property>
    <property name="plugin-14" type="string" value="launcher">
      <property name="items" type="array">
        <value type="string" value="15160485923.desktop"/>
      </property>
    </property>
    <property name="plugin-12" type="string" value="pulseaudio">
      <property name="enable-keyboard-shortcuts" type="bool" value="true"/>
    </property>
  </property>
  <property name="configver" type="int" value="2"/>
</channel>
' > ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
}

echo Updating system
printf "\n"
sleep 1
$( echo update && echo update successful)  || $(echo "Update failed" && exit 1)
printf "\n"

echo Installing software
sleep 1
$( echo installation && echo software installed) || $( echo Installation failed, some were installed, see log printf "\n" && exit 1)

echo Configuring GRUB
sleep 1
$( echo "grub" && echo GRUB configured and updated ) || $(echo "configuring GRUB failed, system might be fucked, good luck." && exit 1)
printf "\n"

echo Setting device specific Setting
sleep 1
$( echo linux-samus && echo "linux-samus used successfully, audio should be fine now" ) || $(echo "Something went wrong" && exit 1)
printf "\n"

echo Setting keyboard binds
sleep 1
$( echo keybind && echo "Key binding set") || $(echo Key binding failed, moving on. && exit 1)
printf "\n"

echo Done, enjoy,

#TODO set themes, I dont think that works yet
#TODO check virtualbox, i think further modules are needed, maybe set a machine
#TODO add verbose
